#! python3
# Regenerates cinbase-rs/src/data/marks.rs: the code points whose Unicode general
# category is Mn, Me or Mc, as seen by the Python that runs the backend
# (python/python3, 3.12 => Unicode 15.0). textclusters._isExtender uses exactly
# unicodedata.category(ch) in ("Mn", "Me", "Mc").
#
#   python\python3\python.exe cinbase-rs\tests\fixtures\gen_marks.py > cinbase-rs\src\data\marks.rs
import sys
import unicodedata

ranges = []
start = None
for cp in range(0x110000):
    mark = unicodedata.category(chr(cp)) in ("Mn", "Me", "Mc")
    if mark and start is None:
        start = cp
    elif not mark and start is not None:
        ranges.append((start, cp - 1))
        start = None
if start is not None:
    ranges.append((start, 0x10FFFF))

out = []
out.append("//! Generated by cinbase-rs/tests/fixtures/gen_marks.py from Python %s's unicodedata" % sys.version.split()[0])
out.append("//! (Unicode %s): code points of general category Mn, Me or Mc. Do not edit." % unicodedata.unidata_version)
out.append("")
out.append("pub const UNIDATA_VERSION: &str = \"%s\";" % unicodedata.unidata_version)
out.append("")
out.append("/// Sorted, non-overlapping inclusive ranges.")
out.append("pub static MARK_RANGES: &[(u32, u32)] = &[")
for a, b in ranges:
    out.append("    (0x%04X, 0x%04X)," % (a, b))
out.append("];")
out.append("")
out.append("/// unicodedata.category(ch) in (\"Mn\", \"Me\", \"Mc\")")
out.append("pub fn is_mark(ch: char) -> bool {")
out.append("    let cp = ch as u32;")
out.append("    MARK_RANGES")
out.append("        .binary_search_by(|&(lo, hi)| {")
out.append("            if hi < cp {")
out.append("                std::cmp::Ordering::Less")
out.append("            } else if lo > cp {")
out.append("                std::cmp::Ordering::Greater")
out.append("            } else {")
out.append("                std::cmp::Ordering::Equal")
out.append("            }")
out.append("        })")
out.append("        .is_ok()")
out.append("}")
sys.stdout.buffer.write(("\n".join(out) + "\n").encode("ascii"))
