//! Port of python/candidate_theme.py: resolving the candidate window theme and
//! the custom colors sent with customizeUI.

use crate::config::{py_strip, CinBaseConfig};
use crate::env;
use serde_json::{Map, Value};
use std::cell::Cell;

/// The fixed colors of the old light candidate window (LEGACY_LIGHT_CANDIDATE_COLORS).
pub const LEGACY_LIGHT_CANDIDATE_COLORS: &[(&str, &str)] = &[
    ("panelBackground", "#FFFFFF"),
    ("panelBorder", "#DADDE3"),
    ("textPrimary", "#20242A"),
    ("textSecondary", "#6B7280"),
    ("highlightBackground", "#DCEBFF"),
    ("highlightBorder", "#9CC7FF"),
    ("highlightText", "#0B3A75"),
];

/// KNOWN_CANDIDATE_THEMES (normalized: alphanumerics only, lower case)
pub const KNOWN_CANDIDATE_THEMES: &[&str] = &[
    "system", "followsystem", "auto",
    "graphite", "dark", "night",
    "sepiadim", "sepia",
    "plum",
    "light",
    "pureblack", "black", "oled",
    "highcontrast", "contrast",
];

thread_local! {
    /// _systemThemeCache: (light, ts)
    static SYSTEM_THEME_CACHE: Cell<(Option<bool>, f64)> = const { Cell::new((None, 0.0)) };
}

/// systemPrefersLightTheme(): the Windows app theme, cached for 5 seconds.
pub fn system_prefers_light_theme() -> bool {
    let now = env::time();
    let (cached, ts) = SYSTEM_THEME_CACHE.with(|c| c.get());
    if let Some(light) = cached {
        if now - ts < 5.0 {
            return light;
        }
    }
    let light = env::system_prefers_light_theme();
    SYSTEM_THEME_CACHE.with(|c| c.set((Some(light), now)));
    light
}

#[cfg(test)]
pub fn reset_system_theme_cache() {
    SYSTEM_THEME_CACHE.with(|c| c.set((None, 0.0)));
}

/// ''.join(ch.lower() for ch in theme if ch.isalnum())
fn normalize_theme_name(theme: &str) -> String {
    theme.chars().filter(|c| c.is_alphanumeric()).flat_map(|c| c.to_lowercase()).collect()
}

/// resolveCandidateTheme for a candidateTheme value: "System" (and unknown or
/// retired themes) resolve to "Light" / "Graphite"; known themes are returned
/// as written.
pub fn resolve_theme_name(theme: &str) -> String {
    let normalized = normalize_theme_name(theme);
    if !KNOWN_CANDIDATE_THEMES.contains(&normalized.as_str()) || matches!(normalized.as_str(), "system" | "followsystem" | "auto") {
        return if system_prefers_light_theme() { "Light".into() } else { "Graphite".into() };
    }
    theme.to_string()
}

/// resolveCandidateTheme(cfg)
pub fn resolve_candidate_theme(cfg: &CinBaseConfig) -> String {
    resolve_theme_name(&cfg.candidate_theme)
}

/// candidateColorsForTheme for raw values: the user's colors, or {} when they
/// are just the old light defaults and another theme is selected.
pub fn colors_for_theme(colors: &Value, theme: &str) -> Map<String, Value> {
    let colors = match colors {
        Value::Object(m) if !m.is_empty() => m,
        _ => return Map::new(),
    };
    let theme = normalize_theme_name(theme);
    let same_keys = colors.len() == LEGACY_LIGHT_CANDIDATE_COLORS.len()
        && LEGACY_LIGHT_CANDIDATE_COLORS.iter().all(|(k, _)| colors.contains_key(*k));
    if same_keys {
        let legacy = LEGACY_LIGHT_CANDIDATE_COLORS.iter().all(|(key, value)| match colors.get(*key) {
            // str(value).strip().lower(): only a string can equal "#xxxxxx"
            Some(Value::String(s)) => py_strip(s).to_lowercase() == value.to_lowercase(),
            _ => false,
        });
        if legacy && theme != "" && theme != "light" {
            return Map::new();
        }
    }
    colors.clone()
}

/// candidateColorsForTheme(cfg)
pub fn candidate_colors_for_theme(cfg: &CinBaseConfig) -> Map<String, Value> {
    colors_for_theme(&Value::Object(cfg.candidate_colors.clone()), &cfg.candidate_theme)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn legacy() -> Value {
        let mut m = Map::new();
        for (k, v) in LEGACY_LIGHT_CANDIDATE_COLORS {
            m.insert(k.to_string(), Value::String(v.to_string()));
        }
        Value::Object(m)
    }

    /// Expected values from python/candidate_theme.py
    /// (tests/fixtures/candidate_theme_cases.json, generated by gen_config_fixtures.py).
    #[test]
    fn matches_python() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/candidate_theme_cases.json");
        let cases: Value = serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
        let mut n = 0;
        for case in cases["resolve"].as_array().unwrap() {
            let theme = case["theme"].as_str().unwrap();
            for (light, key) in [(true, "light"), (false, "dark")] {
                // the registry read is env::system_prefers_light_theme(); emulate it through the cache
                SYSTEM_THEME_CACHE.with(|c| c.set((Some(light), env::time())));
                assert_eq!(resolve_theme_name(theme), case[key].as_str().unwrap(), "theme {:?} light={}", theme, light);
                n += 1;
            }
        }
        for case in cases["colors"].as_array().unwrap() {
            let got = colors_for_theme(&case["colors"], case["theme"].as_str().unwrap());
            assert_eq!(Value::Object(got), case["expected"], "{}", case);
            n += 1;
        }
        assert!(n > 40);
    }

    #[test]
    fn cache_holds_for_five_seconds() {
        reset_system_theme_cache();
        SYSTEM_THEME_CACHE.with(|c| c.set((Some(false), env::time())));
        assert!(!system_prefers_light_theme());
        SYSTEM_THEME_CACHE.with(|c| c.set((Some(false), env::time() - 6.0)));
        // expired: re-read (whatever the machine says), then cached again
        let now = system_prefers_light_theme();
        assert_eq!(SYSTEM_THEME_CACHE.with(|c| c.get()).0, Some(now));
    }

    #[test]
    fn legacy_colors_dropped_for_dark_themes() {
        assert!(colors_for_theme(&legacy(), "Graphite").is_empty());
        assert_eq!(colors_for_theme(&legacy(), "Light").len(), 7);
        assert_eq!(colors_for_theme(&legacy(), "").len(), 7);
        assert!(colors_for_theme(&json!([1]), "Light").is_empty());
    }
}
